export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAIL = 'GET_PHOTOS_FAIL';
export const LOAD_PHOTO_BY_YEAR = 'LOAD_PHOTO_BY_YEAR';
export const LOAD_PHOTO_BY_YEAR_SUCCESS = 'LOAD_PHOTO_BY_YEAR_SUCCESS';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
export const LOAD_MORE_PHOTO = 'LOAD_MORE_PHOTO';
export const OPEN_IMG = 'OPEN_IMG';